### ISSUE TITLE
Adding volume handle to assets URL allows access

### ISSUE THREAD

**Issue by DavidOliver** [OscarBarrett/craft-asset-lockdown#1]
`/admin/assets/` is denied, as expected.

`/admin/assets/volume-handle` is not denied.

If a CMS user has already accessed an assets volume in the assets area, they may well re-request such a page, either intentionally or inadvertently.

Changing `sizeof($request->segments) === 1` to `sizeof($request->segments) >= 1` in the condition resolves this.

Thanks!

**Comment by OscarBarrett** [comment]
Thanks for reporting! Fixed in [1.0.1](https://github.com/OscarBarrett/craft-asset-lockdown/releases/tag/1.0.1).
